
runtime: nodejs16

instance_class: F2

env_variables: 
  BUCKET_NAME: "drybulb_frontend"

handlers:
- url: /
  static_files: dist/angular-tour-of-heroes/index.html
  upload: dist/angular-tour-of-heroes/index.html

- url: /
  static_dir: dist/angular-tour-of-heroes